# Generated by Django 4.2.19 on 2025-04-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_num', models.IntegerField(verbose_name='Номер статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('punishment_type', models.CharField(choices=[('Fine', 'Штраф'), ('Arrest', 'Арест'), ('Community Service', 'Общественные работы'), ('Death', 'Смертная казнь')], max_length=20, verbose_name='Тип наказания')),
                ('numerical_value', models.IntegerField(verbose_name='Числовое значение')),
                ('punishment_type_relapse', models.CharField(choices=[('Fine', 'Штраф'), ('Arrest', 'Арест'), ('Community Service', 'Общественные работы'), ('Death', 'Смертная казнь')], max_length=20, verbose_name='Тип наказания при рецидиве')),
                ('numerical_value_relapse', models.IntegerField(verbose_name='Числовое значение при рецидиве')),
            ],
        ),
        migrations.CreateModel(
            name='FederalWanted',
            fields=[
                ('fi', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField(default=1, verbose_name='ID человека')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('article_num', models.IntegerField(verbose_name='Номер статьи')),
            ],
        ),
        migrations.CreateModel(
            name='LocalCriminals',
            fields=[
                ('cs', models.AutoField(primary_key=True, serialize=False)),
                ('article_num', models.IntegerField(default=0, verbose_name='Номер статьи')),
                ('person_id', models.IntegerField(default=0, verbose_name='ID человека')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('arrest_time', models.DateField(verbose_name='Дата ареста')),
                ('final_panishment', models.TextField(blank=True, verbose_name='Окончательное наказание')),
            ],
        ),
        migrations.CreateModel(
            name='Panishment',
            fields=[
                ('panishment_num', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField(default=0, verbose_name='ID человека')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('article_num', models.IntegerField(verbose_name='Номер статьи')),
                ('punishment_type', models.CharField(choices=[('Fine', 'Штраф'), ('Arrest', 'Арест'), ('Community Service', 'Общественные работы'), ('Death', 'Смертная казнь')], max_length=20, verbose_name='Тип наказания')),
                ('numerical_value', models.IntegerField(verbose_name='Числовое значение')),
                ('fi_flag', models.IntegerField(choices=[(0, 'Локальное'), (1, 'Федеральное')], verbose_name='Статус дела')),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.localcriminals', verbose_name='Номер дела')),
            ],
        ),
    ]
